[package]
name = "mlapibot-ocr"
version = "0.1.0"
edition = "2024"

[dependencies]
mlapibot-common = { path = "../mlapibot-common" }

thiserror = { workspace = true }
tempfile = { workspace = true }
image = { workspace = true }

leptess = { git = "https://github.com/CheAle14/leptess" }
ab_glyph = "0.2.28"
imageproc = { version = "0.25.0", default-features = false }
