[package]
edition = "2024"
name = "mlapibot-ocr"
version = "0.1.0"

[dependencies]
mlapibot-common = { path = "../mlapibot-common" }

ab_glyph = { workspace = true }
image = { workspace = true }
imageproc = { workspace = true }
leptess = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
