[package]
edition = "2024"
name = "mlapibot-reddit"
version = "0.1.0"

[features]
imgur = []

[dependencies]
mlapibot-analysis = { path = "../mlapibot-analysis" }
mlapibot-api = { path = "../mlapibot-api" }
mlapibot-common = { path = "../mlapibot-common" }
mlapibot-database-v2 = { path = "../mlapibot-database-v2" }
mlapibot-imgur = { path = "../mlapibot-imgur" }
mlapibot-markdown = { path = "../mlapibot-markdown" }
mlapibot-ocr = { path = "../mlapibot-ocr" }
mlapibot-webhook = { path = "../mlapibot-webhook" }

annotate-snippets = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bumpalo = { workspace = true, features = ["allocator_api", "collections"] }
chrono = { workspace = true }
chrono-tz = { workspace = true }
futures-util = { workspace = true }
image = { workspace = true }
markdown = { workspace = true }
octocrab = { workspace = true }
ord-many = { workspace = true }
reqwest = { workspace = true }
roux = { workspace = true, features = ["json-error-path", "log-json-on-error"] }
serde = { workspace = true }
serde_json = { workspace = true }
statuspage = { workspace = true }
strsim = { workspace = true }
systemd_socket = { workspace = true }
tempfile = { workspace = true }
tera = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
unic-emoji-char = { workspace = true }
