[package]
edition = "2024"
name = "mlapibot-database-v2"
version = "0.1.0"

[dependencies]
mlapibot-common = { path = "../mlapibot-common" }

chrono = { workspace = true }
futures = { workspace = true }
postgres-types = { workspace = true, features = [
    "derive",
    "with-serde_json-1",
] }
serde = { workspace = true, features = ["derive"] }
statuspage = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
