[workspace]
resolver = "2"
members = [
    "bin/mlapibot-bin",
    "crates/mlapibot-analysis",
    "crates/mlapibot-common",
    "crates/mlapibot-datastore",
    "crates/mlapibot-imgur",
    "crates/mlapibot-ocr",
    "crates/mlapibot-reddit",
    "crates/mlapibot-webhook",
]

[workspace.dependencies]
anyhow = "1.0.86"
thiserror = "2.0.12"
tempfile = "3.18.0"
reqwest = { version = "0.12.5", features = ["blocking", "json", "multipart"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.140"
tera = { version = "1.20.0", default-features = false }
image = { version = "0.25.1", default-features = false, features = [
    "png",
    "jpeg",
] }
ord-many = { git = "https://github.com/CheAle14/ord-many.git" }
