[workspace]
resolver = "2"
members = [
    "bin/mlapibot-bin",
    "crates/mlapibot-analysis",
    "crates/mlapibot-common",
    "crates/mlapibot-datastore",
    "crates/mlapibot-imgur",
    "crates/mlapibot-markdown",
    "crates/mlapibot-ocr",
    "crates/mlapibot-reddit",
    "crates/mlapibot-webhook",
    "tests",
]

[workspace.dependencies]
async-trait = "0.1.89"
anyhow = "1.0.86"
chrono = { version = "0.4.38", features = ["serde"] }
thiserror = "2.0.12"
tempfile = "3.18.0"
tokio = { version = "1.49.0", features = ["full"] }
reqwest = { version = "0.12.5", features = ["json", "multipart"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.140"
tera = { version = "1.20.0", default-features = false }
image = { version = "0.25.1", default-features = false, features = [
    "png",
    "jpeg",
] }
ord-many = { git = "https://github.com/CheAle14/ord-many.git" }
