[package]
edition = "2024"
name = "mlapibot-analysis"
version = "0.1.0"

[dependencies]
mlapibot-common = { path = "../mlapibot-common" }
mlapibot-ocr = { path = "../mlapibot-ocr" }

futures = { workspace = true }
hex_color = { workspace = true, features = ["serde"] }
image = { workspace = true }
ord-many = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
strsim = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
