[package]
edition = "2024"
name = "mlapibot-common"
version = "0.1.0"

[dependencies]
base64ct = { workspace = true }
digest-io = { workspace = true }
ord-many = { workspace = true }
rust-stemmers = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
